import os,signal,subprocess,time,shutil,sqlite3
from pathlib import Path
bridge=Path.home()/"Library/Application Support/Indexa/bridge.sqlite"
if bridge.exists():
 with sqlite3.connect(bridge.as_uri()+"?mode=ro",uri=True) as db:
  if db.execute("SELECT 1 FROM tasks WHERE state IN ('submitting','running','waiting_for_approval','stopping') LIMIT 1").fetchone():
   raise SystemExit("Active task: finish or stop it in Indexa before installing.")
rows=subprocess.check_output(['/bin/ps','-axo','pid=,ppid=,comm='],text=True).splitlines()
processes=[row.strip().split(None,2) for row in rows]
installed=__import__('pathlib').Path.home()/'Applications/Indexa.app'
roots={int(pid) for pid,parent,comm in processes if comm==str(installed/'Contents/MacOS/Indexa')}
owned=set(roots)
while True:
 children={int(pid) for pid,parent,comm in processes if int(parent) in owned}
 if children <= owned:break
 owned.update(children)
# Let the Matrix supervisor drain PostgreSQL/MAS; never terminate database children first.
direct={int(pid) for pid,parent,comm in processes if int(parent) in roots}
for pid in roots | direct:
 try:os.kill(pid,signal.SIGTERM)
 except ProcessLookupError:pass
for _ in range(600):
 alive=[]
 for pid in owned:
  try:os.kill(pid,0);alive.append(pid)
  except ProcessLookupError:pass
 if not alive:break
 time.sleep(.1)
else:raise SystemExit('Services still stopping; update deferred.')
subprocess.run(['/usr/bin/ditto','dist/Indexa.app',str(installed)],check=True)
# Remove generated bytecode from older builds; new builds disable bundle writes.
for cache in (installed/'Contents/Resources/matrix').glob('__pycache__'):
 shutil.rmtree(cache)
subprocess.run(['/usr/bin/codesign','--verify','--deep','--strict',str(installed)],check=True)
print('Updated Indexa; services stopped.')
