import os,signal,subprocess,time,shutil
rows=subprocess.check_output(['/bin/ps','-axo','pid=,ppid=,comm='],text=True).splitlines()
processes=[row.strip().split(None,2) for row in rows]
roots={int(pid) for pid,parent,comm in processes if comm=='/Users/fine/Applications/Indexa.app/Contents/MacOS/Indexa'}
owned=set(roots)
while True:
 children={int(pid) for pid,parent,comm in processes if int(parent) in owned}
 if children <= owned:break
 owned.update(children)
for pid in owned-roots:
 try:os.kill(pid,signal.SIGTERM)
 except ProcessLookupError:pass
for pid in roots:
 try:os.kill(pid,signal.SIGTERM)
 except ProcessLookupError:pass
for _ in range(100):
 alive=[]
 for pid in owned:
  try:os.kill(pid,0);alive.append(pid)
  except ProcessLookupError:pass
 if not alive:break
 time.sleep(.1)
else:raise SystemExit('Services still stopping; update deferred.')
subprocess.run(['/usr/bin/ditto','dist/Indexa.app','/Users/fine/Applications/Indexa.app'],check=True)
# Remove generated bytecode from older builds; new builds disable bundle writes.
for cache in __import__('pathlib').Path('/Users/fine/Applications/Indexa.app/Contents/Resources/matrix').glob('__pycache__'):
 shutil.rmtree(cache)
subprocess.run(['/usr/bin/codesign','--verify','--deep','--strict','/Users/fine/Applications/Indexa.app'],check=True)
print('Updated Indexa; services stopped.')
