import os,signal,subprocess,time,shutil,sqlite3
from pathlib import Path
bridge=Path.home()/"Library/Application Support/Indexa/bridge.sqlite"
if bridge.exists():
 with sqlite3.connect(bridge.as_uri()+"?mode=ro",uri=True) as db:
  if db.execute("SELECT 1 FROM tasks WHERE state IN ('submitting','running','waiting_for_approval','stopping') LIMIT 1").fetchone():
   raise SystemExit("Active task: finish or stop it in Indexa before installing.")
rows=subprocess.check_output(['/bin/ps','-axo','pid=,ppid=,comm='],text=True).splitlines()
processes=[row.strip().split(None,2) for row in rows]
installed=Path('/Applications/Indexa.app')
legacy=Path.home()/'Applications/Indexa.app'
# Migrate only our own bundle, never an unrelated app at the destination.
import plistlib
for bundle in (installed,legacy,Path('dist/Indexa.app')):
 if bundle.exists():
  info=plistlib.loads((bundle/'Contents/Info.plist').read_bytes())
  if info.get('CFBundleIdentifier')!='local.fine.indexa':
   raise SystemExit('Refusing to replace an unrelated application: '+str(bundle))
roots={int(pid) for pid,parent,comm in processes if comm in {str(bundle/'Contents/MacOS/Indexa') for bundle in (installed,legacy)}}
owned=set(roots)
while True:
 children={int(pid) for pid,parent,comm in processes if int(parent) in owned}
 if children <= owned:break
 owned.update(children)
# Let the Matrix supervisor drain PostgreSQL/MAS; never terminate database children first.
direct={int(pid) for pid,parent,comm in processes if int(parent) in roots}
for pid in roots | direct:
 try:os.kill(pid,signal.SIGTERM)
 except ProcessLookupError:pass
for _ in range(600):
 alive=[]
 for pid in owned:
  try:os.kill(pid,0);alive.append(pid)
  except ProcessLookupError:pass
 if not alive:break
 time.sleep(.1)
else:raise SystemExit('Services still stopping; update deferred.')
if legacy.exists() and not installed.exists():
 shutil.move(str(legacy),str(installed))
subprocess.run(['/usr/bin/ditto','dist/Indexa.app',str(installed)],check=True)
# Remove generated bytecode from older builds; new builds disable bundle writes.
for cache in (installed/'Contents/Resources/matrix').glob('__pycache__'):
 shutil.rmtree(cache)
subprocess.run(['/usr/bin/codesign','--verify','--deep','--strict',str(installed)],check=True)
if legacy.exists():shutil.rmtree(legacy)
subprocess.run(['/usr/bin/open',str(installed)],check=True)
print('Updated and launched /Applications/Indexa.app.')
